Repository MicrosoftDocs/CommunityToolkit, pull requests merged in 2022-05, with the labels that each got.

#92 Add Multi-Binding Docs
  docs/maui/markup/extensions/bindable-object-extensions.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, dotnet-communitytoolkit/prod

#93 Add DynamicResourceHandler Extensions
  docs/maui/TOC.yml
  docs/maui/markup/extensions/dynamic-resource-handler-extensions.md
  docs/maui/markup/markup.md
Labels: needs-human-review, do-not-merge

#95 Add CompareConverter
  docs/maui/TOC.yml
  docs/maui/converters/compare-converter.md
  docs/maui/converters/index.md
Labels: needs-human-review, do-not-merge

#96 Add grid-extensions.md
  docs/maui/TOC.yml
  docs/maui/markup/extensions/grid-extensions.md
  docs/maui/markup/markup.md
Labels: needs-human-review, do-not-merge

#102 Fixed paths to the API code
  docs/maui/behaviors/characters-validation-behavior.md
  docs/maui/behaviors/email-validation-behavior.md
  docs/maui/behaviors/masked-behavior.md
  docs/maui/behaviors/maximum-length-reached-behavior.md
  docs/maui/behaviors/numeric-validation-behavior.md
  docs/maui/behaviors/required-string-validation-behavior.md
  docs/maui/behaviors/text-validation-behavior.md
  docs/maui/behaviors/uri-validation-behavior.md
Labels: qualifies-for-auto-merge, do-not-merge, Change sent to author, dotnet-communitytoolkit/prod

#100 Add ColorConversionExtensions
  docs/maui/TOC.yml
  docs/maui/extensions/color-conversion-extensions.md
  docs/maui/extensions/index.md
Labels: needs-human-review, do-not-merge

#99 Add TextColorTo
  docs/maui/extensions/color-animation-extensions.md
Labels: needs-human-review, do-not-merge

#97 Add SetFocusOnEntryCompletedBehavior
  docs/maui/TOC.yml
  docs/maui/behaviors/characters-validation-behavior.md
  docs/maui/behaviors/email-validation-behavior.md
  docs/maui/behaviors/event-to-command-behavior.md
  docs/maui/behaviors/index.md
  docs/maui/behaviors/masked-behavior.md
  docs/maui/behaviors/maximum-length-reached-behavior.md
  docs/maui/behaviors/numeric-validation-behavior.md
  docs/maui/behaviors/progressbar-animation-behavior.md
  docs/maui/behaviors/required-string-validation-behavior.md
  docs/maui/behaviors/set-focus-when-entry-completed-behavior.md
  docs/maui/behaviors/text-validation-behavior.md
  docs/maui/behaviors/uri-validation-behavior.md
  docs/maui/behaviors/user-stopped-typing-behavior.md
Labels: needs-human-review, do-not-merge

#103 Add Label extensions
  docs/maui/TOC.yml
  docs/maui/markup/extensions/label-extensions.md
  docs/maui/markup/markup.md
Labels: needs-human-review, do-not-merge

#104 Add TextAlignment Extensions
  docs/maui/TOC.yml
  docs/maui/markup/extensions/text-alignment-extensions.md
  docs/maui/markup/markup.md
Labels: needs-human-review, do-not-merge

#105 Add View Extensions
  docs/maui/TOC.yml
  docs/maui/markup/extensions/view-extensions.md
  docs/maui/markup/markup.md
Labels: needs-human-review, do-not-merge

#108 Add VariableMultiValueConverter
  docs/maui/TOC.yml
  docs/maui/converters/index.md
  docs/maui/converters/variable-multi-value-converter.md
Labels: needs-human-review, do-not-merge

#89 MathExpressionConverter and MultiMathExpressionConverter
  docs/maui/TOC.yml
  docs/maui/converters/index.md
  docs/maui/converters/math-expression-converter.md
  docs/maui/converters/multi-math-expression-converter.md
  docs/maui/includes/math-expression-operations.md
Labels: needs-human-review, do-not-merge, review-team-triage

#98 Add MultiValidationBehavior
  docs/maui/TOC.yml
  docs/maui/behaviors/index.md
  docs/maui/behaviors/multi-validation-behavior.md
Labels: needs-human-review, do-not-merge
