Repository MicrosoftDocs/CommunityToolkit, pull requests merged in 2022-04, with the labels that each got.

#47 Create element-extensions.md
  docs/maui/TOC.yml
  docs/maui/markup/extensions/element-extensions.md
Labels: needs-human-review, do-not-merge

#51 Port MVVM Toolkit docs
  .openpublishing.redirection.json
  docs/TOC.yml
  docs/dotnet/TOC.yml
  docs/images/get-started/manage-nuget-packages.png
  docs/index.yml
  docs/introduction.md
  docs/mvvm/AsyncRelayCommand.md
  docs/mvvm/Introduction.md
  docs/mvvm/Ioc.md
  docs/mvvm/Messenger.md
  docs/mvvm/MigratingFromMvvmBasic.md
  docs/mvvm/MigratingFromMvvmLight.md
  docs/mvvm/ObservableGroupedCollections.md
  docs/mvvm/ObservableObject.md
  docs/mvvm/ObservableRecipient.md
  docs/mvvm/ObservableValidator.md
  docs/mvvm/PuttingThingsTogether.md
  docs/mvvm/RelayCommand.md
Labels: needs-human-review, do-not-merge

#65 Add Views to the landing page
  docs/index.yml
Labels: needs-human-review, do-not-merge, review-team-triage

#67 BoolToObjectConverter
  docs/maui/TOC.yml
  docs/maui/converters/bool-to-object-converter.md
  docs/maui/converters/index.md
Labels: needs-human-review, do-not-merge

#55 Add additional Snackbar WinUI notes
  docs/maui/alerts/snackbar.md
Labels: needs-human-review, do-not-merge

#61 User stopped typing behavior
  docs/maui/behaviors/index.md
  docs/maui/behaviors/user-stopped-typing-behavior.md
Labels: needs-human-review, do-not-merge

#76 Add ColorAnimationExtensions
  docs/maui/TOC.yml
  docs/maui/alerts/index.md
  docs/maui/behaviors/index.md
  docs/maui/extensions/color-animation-extensions.md
  docs/maui/extensions/index.md
  docs/maui/views/index.md
Labels: needs-human-review, do-not-merge

#80 Fix ColorAnimationsExtensions formatting
  docs/maui/extensions/color-animation-extensions.md
Labels: qualifies-for-auto-merge, do-not-merge

#82 Update DrawingView.md
  docs/maui/views/DrawingView.md
Labels: qualifies-for-auto-merge, do-not-merge
