Repository MicrosoftDocs/CommunityToolkit, pull requests merged in 2023-01, with the labels that each got.

#166 Docs for new MAUI.Markup methods for VisualElement
  docs/maui/markup/extensions/visual-element-extensions.md
Labels: ready-to-merge, dotnet-communitytoolkit/prod

#190 Fix links of the index page
  docs/index.yml
Labels: do-not-merge, Change sent to author, dotnet-communitytoolkit/prod

#192 Update toast.md
  docs/maui/alerts/toast.md
Labels: do-not-merge

#183 Update StateContainer Documentation
  docs/maui/layouts/StateContainer.md
Labels: do-not-merge, Change sent to author, dotnet-communitytoolkit/prod

#205 Fix paths of .NET Community Toolkit index files
  docs/index.yml
Labels: bug
